export enum GalleryTypeEnum {
  REZBA = 'rezba',
  PLAZMA = 'plazma',
  LAST_WORKS = 'last-works',
  FREZEROVKA = 'frezerovka',
  THREED_PANEL = '3dpanel',
  LASER_CUTTING = 'laser-cutting',
  MIRROR_FRAMES = 'mirror-frames',
  FORGING = 'forging',
  INDUSTRIAL = 'industrial',
  BRAZIERS = 'braziers',
  METAL = 'metal',
  STAIRS = 'stairs',
  LETTERS = 'letters',
  LOFT = 'loft',
  GOAL = 'goal',
  RAILING = 'railing',
  METALDECOR = 'metaldecor',
  ALUMINUM = 'aluminum',
  BRASS = 'brass',
  METALCUTTING = 'metalcutting',
  DECORMETAL = 'decormetal',
  FURNITURE = 'furniture',
}
